/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_faftextdemo_free: (a: number, b: number) => void;
export const faftextdemo_attach: (a: any, b: number, c: number) => any;
export const faftextdemo_backend: (a: number) => [number, number];
export const faftextdemo_caret_css_rect: (a: number) => [number, number];
export const faftextdemo_composition_end: (a: number, b: number) => void;
export const faftextdemo_composition_start: (a: number) => void;
export const faftextdemo_composition_update: (a: number, b: number, c: number) => void;
export const faftextdemo_insert_text: (a: number, b: number, c: number) => void;
export const faftextdemo_key_input: (a: number, b: number, c: number, d: number, e: number) => number;
export const faftextdemo_pointer_down: (a: number, b: number, c: number) => void;
export const faftextdemo_pointer_move: (a: number, b: number, c: number) => void;
export const faftextdemo_pointer_up: (a: number) => void;
export const faftextdemo_render: (a: number) => [number, number, number];
export const faftextdemo_resize: (a: number, b: number, c: number, d: number) => void;
export const faftextdemo_selected_text: (a: number) => [number, number];
export const faftextdemo_set_caret_visible: (a: number, b: number) => void;
export const faftextdemo_set_font_size: (a: number, b: number) => void;
export const faftextdemo_set_search: (a: number, b: number, c: number) => void;
export const faftextdemo_set_search_mode: (a: number, b: number, c: number) => void;
export const faftextdemo_set_terminal: (a: number, b: number) => void;
export const faftextdemo_set_text: (a: number, b: number, c: number) => void;
export const faftextdemo_set_tilt: (a: number, b: number) => void;
export const faftextdemo_set_weight_blend: (a: number, b: number) => void;
export const faftextdemo_terminal: (a: number) => number;
export const faftextdemo_text: (a: number) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h6eb6ae39273879d5: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h2cdb68df6893a714: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h2cdb68df6893a714_2: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h2cdb68df6893a714_3: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h97af8ec3bf76bae8: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
